### PR TITLE
Use backport v5.6.6

### PR DESCRIPTION
**Pull request by negz**
Fixes https://github.com/sqren/backport-github-action/issues/5

I ran into the issue above; making this change appears to fix it.

### CODE REVIEW

**Comment by mtupitsyn** [comment]
Hi @sqren! The plugin and backport tool look really great, but https://github.com/sqren/backport-github-action/issues/5 is essentially killing it... Any chance you could review and merge a fix proposed by @negz?

**Comment by mtupitsyn** [comment]
@sqren Thank you for merging the fix! Is there going to be a release soon?

**Comment by sqren** [comment]
Done, released as 1.0.41

**Comment by sqren** [comment]
That being said, this action has mostly been replaced by https://github.com/elastic/kibana-github-actions/tree/main/backport. You can see it used [here](https://github.com/elastic/kibana/blob/master/.github/workflows/backport.yml).

**Comment by mtupitsyn** [comment]
Thank you, I'll take a look!

**Pull request merged**
